### ISSUE TITLE
 Can you please help me? I am trying to run your code but it is throwing me an error. Please try to ressolve it

### ISSUE THREAD

**Issue by ruchi-sharma1** [sujanshirol/Test-Summarization-LSTMs#1]
Can you please help me? I am trying to run your code but it is throwing me an error in attn_out, attn_states = attn_layer([encoder_outputs, decoder_outputs]) line and the error is                                                                                                                                                                                     TypeError: Exception encountered when calling layer "tf.keras.backend.rnn" (type TFOpLambda).  You are passing KerasTensor(type_spec=TensorSpec(shape=(None, 30), dtype=tf.float32, name=None), name='tf.compat.v1.nn.softmax_1/Softmax:0', description="created by layer 'tf.compat.v1.nn.softmax_1'"), an intermediate Keras symbolic input/output, to a TF API that does not allow registering custom dispatchers, such as `tf.cond`, `tf.function`, gradient tapes, or `tf.map_fn`. Keras Functional model construction only supports TF API calls that *do* support dispatching, such as `tf.math.add` or `tf.reshape`. Other APIs cannot be called directly on symbolic Kerasinputs/outputs. You can work around this limitation by putting the operation in a custom Keras layer `call` and calling that layer on this symbolic input/output.

**Comment by Maria2244** [comment]
you must add Attention layer file in same dirctory

**Comment by AnjaliVanam** [comment]
how

**Comment by vinayparjapati5** [comment]
Yes first add attention.py
